# registration for scan to map
registration:
    registration_method: NDT_OMP
    ICP:
        max_corr_dist : 1.2
        trans_eps : 0.01
        euc_fitness_eps : 0.36
        max_iter : 30
    ICP_SVD:
        max_corr_dist : 1.2
        trans_eps : 0.01
        euc_fitness_eps : 0.36
        max_iter : 10
    NDT:
        res : 1.0
        step_size : 0.1
        trans_eps : 0.01
        max_iter : 30

# for local map
key_frame_distance: 2.0
local_frame_num: 20
local_map_filter:
    filter_method: voxel_filter
    voxel_filter:
        leaf_size: [0.6, 0.6, 0.6]

# for current scan
current_scan_filter:
    filter_method: voxel_filter
    voxel_filter:
        leaf_size: [1.3, 1.3, 1.3]

# for rviz display
display_filter:
    filter_method: voxel_filter
    voxel_filter:
        leaf_size: [0.6, 0.6, 0.6]
