name: Build and Test
on:
  push:
    branches: [ humble ]
  pull_request:
    branches: [ humble ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-jammy-ros-humble-desktop-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build localization_for_autonomous_driving
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: humble
          skip-tests: true
      - name: Remove flake8-quotes for linter
        run: pip3 uninstall -y flake8-quotes
      - name: Test localization_interfaces
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh localization_interfaces
      - name: Test localization_common
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh localization_common
      - name: Test lidar_odometry
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh lidar_odometry
      - name: Test lidar_mapping
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh lidar_mapping
      - name: Test lidar_localization
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh lidar_localization
      - name: Test kf_based_localization
        run: |
          /usr/bin/bash .github/workflows/colcon_test.sh kf_based_localization
